@personUrl = http://localhost:3001/api/persons

### Get all people
GET {{personUrl}}

### Get a person by id: 200
GET {{personUrl}}/1

### Get a person by id: 404 
### because parameter is not numeric
GET {{personUrl}}/string

### Get a person by id: 404 
### because person not found
GET {{personUrl}}/10

### Add a person: 200
### 400 if person's name already exists
POST {{personUrl}}
Content-Type: application/json

{
  "name": "Alan",
  "number": "123456"
}

### Add a person: 400
### because number is missing
POST {{personUrl}}
Content-Type: application/json

{
  "name": "Alan"
}

### Add a person: 200
### because name is missing
POST {{personUrl}}
Content-Type: application/json

{
  "number": "123456"
}

### Add a person: 200
### because data is missing
POST {{personUrl}}
Content-Type: application/json

### Delete a person by id
DELETE {{personUrl}}/1
